services:
  softgems-node:
    image: ghcr.io/l-atelier-des-chercheurs/softgems:latest
    ports:
      - "8080:8080"
    volumes:
      - softgems-data:/home/node/Documents/softgems
    restart: always

volumes:
  softgems-data:
