export const color_suggestions = [
  "Red",
  "Orangy Red",
  "Orange",
  "Yellow",
  "Yellowish Green",
  "Green",
  "Bluish Green",
  "Greenish Blue",
  "Blue",
  "Violet Blue",
  "Violet",
  "Purple",
  "Light Pink",
  "Pastel Pink",
  "Pink",
  "Intense Pink",
  "Vivid Pink",
  "Purplish Red",
  "Intense Red",
  "Vivid Red",
  "Deep Red",
  "Dark Red",
  "Light Orangy Pink",
  "Pastel Orangy Pink",
  "Pastel Pinkish Orange",
  "Orangy Pink",
  "Pinkish Orange",
  "Intense Orangy Pink",
  "Vivid Orange",
  "Deep Orange",
  "Deep Brownish Red",
  "Brown",
  "Deep Brown",
  "Light Yellow",
  "Pastel Yellow",
  "Intense Yellow",
  "Vivid Yellow",
  "Brownish Yellow",
  "Pastel Yellowish Green",
  "Light Green",
  "Pastel Green",
  "Intense Green",
  "Vivid Yellowish Green",
  "Vivid Green",
  "Deep Yellowish Green",
  "Deep Green",
  "Pastel Bluish Green",
  "Pastel Greenish Blue",
  "Intense Bluish Green",
  "Intense Greenish Blue",
  "Vivid Bluish Green",
  "Vivid Greenish Blue",
  "Deep Bluish Green",
  "Deep Greenish Blue",
  "Light Blue",
  "Pastel Blue",
  "Violetish Blue",
  "Intense Blue",
  "Vivid Blue",
  "Deep Blue",
  "Dark Blue",
  "Light Purple",
  "Pastel Violet",
  "Pastel Purple",
  "Intense Purple",
  "Vivid Violet",
  "Vivid Purple",
  "Deep Violet",
  "Deep Purple",
  "Grey",
  "Black",
  "Pigeon Blood",
  "Royal Blue",
  "Padparadscha",
];
