export const origin_country_suggestions = [
  "Afghanistan",
  "Australia",
  "Brazil",
  "Cambodia",
  "China",
  "Colombia",
  "Ethiopia",
  "India",
  "Kenya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nigeria",
  "Russia",
  "Sri Lanka",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Vietnam",
  "Zambia",
  "Ceylon (Sri Lanka)",
  "East Africa",
  "West Africa",
  "Africa",
  "Kashmir",
  "Panjshir",
  "Unknown",
  "Basalt-related deposit",
];
