export const shape_suggestions = [
  "Round Brilliant",
  "Oval",
  "Cushion",
  "Square Cushion",
  "Pear Shape",
  "Marquise",
  "Heart",
  "Princess",
  "Baguette",
  "Trapezoid",
  "Triangle (Trilliant)",
  "Hexagonal",
  "Octagonal",
  "Octogonal",
  "Lozenge",
  "Fancy Shape",
  "Mixed Cut",
  "Rose Cut",
  "Briolette",
  "Cabochon",
  "Sugarloaf Cabochon",
  "Buff Top",
  "Carved",
  "Pierced",
  "Bead",
  "Drop",
  "Rough",
  "Polished Rough",
];
