export const stone_type_suggestions = [
  "Beryl",
  "Emerald",
  "Aquamarine",
  "Morganite",
  "Heliodor",
  "Corundum",
  "Ruby",
  "Sapphire",
  "Star Ruby",
  "Star Sapphire",
  "Quartz",
  "Amethyst",
  "Citrine",
  "Rose Quartz",
  "Chalcedony",
  "Agate",
  "Tiger's Eye",
  "Feldspar",
  "Moonstone",
  "Sunstone",
  "Garnet",
  "Demantoid Garnet",
  "Tsavorite Garnet",
  "Spessartine Garnet",
  "Hessonite Garnet",
  "Alexandrite",
  "Chrysoberyl",
  "Spinel",
  "Topaz",
  "Tourmaline",
  "Tanzanite",
  "Zircon",
  "Peridot",
  "Diopside",
  "Enstatite",
  "Scapolite",
  "Danburite",
  "Rhodochrosite",
  "Malachite",
  "Amazonite",
  "Lapis Lazuli",
  "Turquoise",
  "Coral",
  "Opal",
  "Cacholong",
  "Ebony",
  "Rosewood",
  "Pearl",
  "Natural Pearl",
  "Cultured Pearl",
  "Precious Stones",
  "Semi-Precious Stones",
];
