export const treatment_type_suggestions = [
  "Natural",
  "No indications of heating",
  "Indications of heating / TE",
  "Indications of heating with residues (TE1/2/3/4/5)",
  "Indications of heating with diffusion (Be/Ti/Cr)",
  "Indications of heating with Lead Glass filling (F1/2/3)",
  "No indications of clarity modification",
  "Oil - Insignificant",
  "Oil - Minor",
  "Oil - Moderate",
  "Oil - Significant",
  "Resin - Insignificant",
  "Resin - Minor",
  "Resin - Moderate",
  "Resin - Significant",
  "Type A (Natural)",
  "Type B (Impregnated)",
];
