export const default_gem_fields = {
  reference_id: "",
  status: "available",
  color: "",
  origin: "",
  dimensions: "",
  gem_type: "",
  weight_carat: 0,
  piece_count: 1,
  condition: "",
  treatment: "",
  purchase_price_usd: 0,
  sale_price_usd: 0,
  price_per_carat_usd: 0,
  supplier: "",
  acquisition_date: "",
  country_of_cut: "",
  pair_gem_id: "",
  remarks: "",
};
